language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

branches:
  only:
    - master

dist: bionic

script:
  - go get -u ./...
  - go test -v github.com/gengzongjie/tokenizer/normalizer
  - go test -v github.com/gengzongjie/tokenizer/model/bpe
  - go test -v github.com/gengzongjie/tokenizer/model/wordpiece
  - go test -v github.com/gengzongjie/tokenizer/pretokenizer
  - go test -v github.com/gengzongjie/tokenizer
